#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_MISSION_ENABLED
#define AP_MISSION_ENABLED 1
#endif

#ifndef AP_MISSION_MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET_ENABLED
#define AP_MISSION_MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET_ENABLED 0
#endif
