#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_CANDRIVER_ENABLED
#define AP_CANDRIVER_ENABLED HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#ifndef AP_CANSENSOR_ENABLED
#define AP_CANSENSOR_ENABLED AP_CANDRIVER_ENABLED
#endif

#ifndef AP_CAN_SLCAN_ENABLED
#define AP_CAN_SLCAN_ENABLED HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif
